[env]
TERM = "xterm-256color"

[window]
padding.x = 8
padding.y = 8

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font Mono"

size = 14

[colors.primary]
background = "#181722"